# Site settings
title: My Corner | Shramona Roy
description: My Corner | Shramona Roy
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shramona Roy
user_description: I'm a thorough-bred Bengali, brought up in Pune and currently living in Chennai. I passed my ICSE 10th std from Pawar Public School, Pune. I did my CBSE 11th & 12th std from City International School, Pune and ended up as one of the city toppers with 97.2% marks in my boards. Presently, I'm pursuing my undergrads in Electronics Engineering at IIITD&M Kancheepuram.
                  
                  I have been into coding since 9th std and started with Front-End Web Development during my 1st year of college. Now I'm in my 2nd year and am working as a Front-End Developer at [Digital Media Team, IIITD&M Kancheepuram](https://github.com/DMT-IIITDM). As of today I'm fairly proficient with Java, C, C++, HTML & CSS and am learning Javascript and Python.
                  
                  Besides engineering and coding, I've always been a Dance enthusiast. I briefly trained as an Odissi dancer and have ever since been in touch with it. Dancing is an indispensable part of my life and I have been a part of multiple semi-classical and contemporary dance teams till date.
                  
                  I'm also somewhat of a bookworm and love the works of Rabindranath Tagore, Jane Austen, Dan Brown and JK Rowling. Apart from this I also enjoy singing and listening to music. I also watch a lot of movies ranging from Hollywood to all time Bengali classics along with more contemporary ones.
                  
                  This is the web corner of a 20 year old having the time of her life doing what she loves with the best people around her. 
user_title: Web Developer, Circuit Designer and Dancer
email: evd17i006@iiitdm.ac.in
twitter_username: lorem_ipsum
github_username:  shramonaroy
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
